// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/backup": {
            "post": {
                "description": "Queue a backup job for the specified database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backup"
                ],
                "summary": "Trigger a database backup",
                "parameters": [
                    {
                        "description": "Backup Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.BackupRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Backup started",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    },
                    "400": {
                        "description": "error: Bad request",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    }
                }
            }
        },
        "/backups": {
            "get": {
                "description": "Get a paginated list of all backups with optional filtering",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backup"
                ],
                "summary": "List all backups",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated status values (pending,generating,completed,failed)",
                        "name": "statuses",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search keyword (searches in database, host, type)",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "createdAt",
                        "description": "Field to order by",
                        "name": "orderBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "desc",
                        "description": "Order direction (asc/desc)",
                        "name": "orderDir",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start date for filtering (RFC3339 format)",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date for filtering (RFC3339 format)",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of backups",
                        "schema": {
                            "$ref": "#/definitions/model.BackupListResponse"
                        }
                    },
                    "500": {
                        "description": "error: Internal server error",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    }
                }
            }
        },
        "/backups/stats": {
            "get": {
                "description": "Retrieve aggregated backup statistics by type and status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backup"
                ],
                "summary": "Get backup statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date for filtering (RFC3339 format)",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date for filtering (RFC3339 format)",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Backup statistics",
                        "schema": {
                            "$ref": "#/definitions/database.BackupStats"
                        }
                    },
                    "500": {
                        "description": "error: Internal server error",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    }
                }
            }
        },
        "/backups/{id}": {
            "get": {
                "description": "Retrieve a single backup by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backup"
                ],
                "summary": "Get a single backup",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Backup ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Backup details",
                        "schema": {
                            "$ref": "#/definitions/model.BackupMetadata"
                        }
                    },
                    "400": {
                        "description": "error: Bad request",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    },
                    "404": {
                        "description": "error: Backup not found",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    },
                    "500": {
                        "description": "error: Internal server error",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a backup from both MongoDB and R2 storage",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backup"
                ],
                "summary": "Delete a backup",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Backup ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Backup deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    },
                    "400": {
                        "description": "error: Bad request",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    },
                    "404": {
                        "description": "error: Backup not found",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    },
                    "500": {
                        "description": "error: Internal server error",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    }
                }
            }
        },
        "/backups/{id}/download": {
            "get": {
                "description": "Generate a presigned URL to download a backup file from R2 storage",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "backup"
                ],
                "summary": "Download a backup file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Backup ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Download URL",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "error: Bad request",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    },
                    "404": {
                        "description": "error: Backup not found",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    },
                    "500": {
                        "description": "error: Internal server error",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    }
                }
            }
        },
        "/databases": {
            "get": {
                "description": "List all saved database configurations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "database"
                ],
                "summary": "List all databases",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.DatabaseListResponse"
                        }
                    },
                    "500": {
                        "description": "error: Internal server error",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Save a new database configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "database"
                ],
                "summary": "Create a new database",
                "parameters": [
                    {
                        "description": "Database Configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateDatabaseRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Database"
                        }
                    },
                    "400": {
                        "description": "error: Bad request",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    },
                    "500": {
                        "description": "error: Internal server error",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    }
                }
            }
        },
        "/databases/{id}": {
            "get": {
                "description": "Retrieve a database configuration by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "database"
                ],
                "summary": "Get a database",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Database"
                        }
                    },
                    "400": {
                        "description": "error: Bad request",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    },
                    "404": {
                        "description": "error: Database not found",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    },
                    "500": {
                        "description": "error: Internal server error",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing database configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "database"
                ],
                "summary": "Update a database",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Database Configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateDatabaseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Database"
                        }
                    },
                    "400": {
                        "description": "error: Bad request",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    },
                    "404": {
                        "description": "error: Database not found",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    },
                    "500": {
                        "description": "error: Internal server error",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a database configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "database"
                ],
                "summary": "Delete a database",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Database deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    },
                    "400": {
                        "description": "error: Bad request",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    },
                    "404": {
                        "description": "error: Database not found",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    },
                    "500": {
                        "description": "error: Internal server error",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    }
                }
            }
        },
        "/databases/{id}/backup": {
            "post": {
                "description": "Manually trigger a backup for a saved database configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "database"
                ],
                "summary": "Trigger a backup for a database",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Backup job submitted successfully",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    },
                    "400": {
                        "description": "error: Bad request",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    },
                    "404": {
                        "description": "error: Database not found",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    },
                    "500": {
                        "description": "error: Internal server error",
                        "schema": {
                            "$ref": "#/definitions/model.BackupResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "database.BackupStats": {
            "type": "object",
            "properties": {
                "byStatus": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "byType": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "model.BackupListResponse": {
            "type": "object",
            "properties": {
                "backups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.BackupMetadata"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "model.BackupMetadata": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "database": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "filePath": {
                    "type": "string"
                },
                "fileSize": {
                    "type": "integer"
                },
                "host": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "objectKey": {
                    "type": "string"
                },
                "status": {
                    "description": "pending, generating, completed, failed",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.BackupStatus"
                        }
                    ]
                },
                "timestamp": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.BackupRequest": {
            "type": "object",
            "properties": {
                "connectionUri": {
                    "type": "string",
                    "example": "mongodb://user:pass@host:port/db"
                },
                "database": {
                    "type": "string",
                    "example": "mydb"
                },
                "host": {
                    "type": "string",
                    "example": "localhost"
                },
                "password": {
                    "type": "string",
                    "example": "pass"
                },
                "port": {
                    "type": "string",
                    "example": "5432"
                },
                "type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.BackupType"
                        }
                    ],
                    "example": "postgre"
                },
                "username": {
                    "type": "string",
                    "example": "user"
                },
                "webhookUrl": {
                    "type": "string",
                    "example": "http://example.com/webhook"
                }
            }
        },
        "model.BackupResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "model.BackupStatus": {
            "type": "string",
            "enum": [
                "pending",
                "generating",
                "completed",
                "failed"
            ],
            "x-enum-varnames": [
                "StatusPending",
                "StatusGenerating",
                "StatusCompleted",
                "StatusFailed"
            ]
        },
        "model.BackupType": {
            "type": "string",
            "enum": [
                "postgre",
                "mysql",
                "mongo",
                "redis"
            ],
            "x-enum-varnames": [
                "Postgres",
                "MySQL",
                "Mongo",
                "Redis"
            ]
        },
        "model.CreateDatabaseRequest": {
            "type": "object",
            "required": [
                "name",
                "type"
            ],
            "properties": {
                "connectionUri": {
                    "type": "string",
                    "example": "mongodb://user:pass@host:port/db"
                },
                "cronExpression": {
                    "type": "string",
                    "example": "0 0 * * *"
                },
                "database": {
                    "type": "string",
                    "example": "mydb"
                },
                "host": {
                    "type": "string",
                    "example": "localhost"
                },
                "isActive": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "My Production DB"
                },
                "password": {
                    "type": "string",
                    "example": "pass"
                },
                "port": {
                    "type": "string",
                    "example": "5432"
                },
                "type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.BackupType"
                        }
                    ],
                    "example": "postgre"
                },
                "username": {
                    "type": "string",
                    "example": "user"
                },
                "webhookUrl": {
                    "type": "string",
                    "example": "http://example.com/webhook"
                }
            }
        },
        "model.Database": {
            "type": "object",
            "properties": {
                "connectionUri": {
                    "type": "string",
                    "example": "mongodb://user:pass@host:port/db"
                },
                "createdAt": {
                    "type": "string"
                },
                "cronExpression": {
                    "type": "string",
                    "example": "0 0 * * *"
                },
                "database": {
                    "type": "string",
                    "example": "mydb"
                },
                "host": {
                    "type": "string",
                    "example": "localhost"
                },
                "id": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "My Production DB"
                },
                "password": {
                    "type": "string",
                    "example": "pass"
                },
                "port": {
                    "type": "string",
                    "example": "5432"
                },
                "type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.BackupType"
                        }
                    ],
                    "example": "postgre"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "example": "user"
                },
                "webhookUrl": {
                    "type": "string",
                    "example": "http://example.com/webhook"
                }
            }
        },
        "model.DatabaseListResponse": {
            "type": "object",
            "properties": {
                "databases": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Database"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "model.UpdateDatabaseRequest": {
            "type": "object",
            "properties": {
                "connectionUri": {
                    "type": "string",
                    "example": "mongodb://user:pass@host:port/db"
                },
                "cronExpression": {
                    "type": "string",
                    "example": "0 0 * * *"
                },
                "database": {
                    "type": "string",
                    "example": "mydb"
                },
                "host": {
                    "type": "string",
                    "example": "localhost"
                },
                "isActive": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "My Production DB"
                },
                "password": {
                    "type": "string",
                    "example": "pass"
                },
                "port": {
                    "type": "string",
                    "example": "5432"
                },
                "type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.BackupType"
                        }
                    ],
                    "example": "postgre"
                },
                "username": {
                    "type": "string",
                    "example": "user"
                },
                "webhookUrl": {
                    "type": "string",
                    "example": "http://example.com/webhook"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Database Backup API",
	Description:      "API for triggering database backups and managing them.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
